name: RandomChunkGenerator
version: '${project.version}'
main: me.sratabix.randomchunk.RandomChunkPlugin
api-version: '1.21'
author: sratabix
description: Lets vanilla generate the world, then randomly corrupts scattered chunks.
